export const GET_ACCOUNTS_LIST = 'GET_ACCOUNTS_LIST';

export const SET_CURRENT_ACCOUNTS_LIST_TYPE = 'SET_CURRENT_ACCOUNTS_LIST_TYPE';

export const SET_CURRENT_ACCOUNTS_PAGE = 'SET_CURRENT_ACCOUNTS_PAGE';

export const GET_ACCOUNTS_LIST_SUCCESS = 'GET_ACCOUNTS_LIST_SUCCESS';

export const GET_ACCOUNTS_LIST_ERROR = 'GET_ACCOUNTS_LIST_ERROR';

export const CREATE_NEW_ACCOUNT = 'CREATE_NEW_ACCOUNT';

export const CREATE_NEW_ACCOUNT_SUCCESS = 'CREATE_NEW_ACCOUNT_SUCCESS';

export const CREATE_NEW_ACCOUNT_ERROR = 'CREATE_NEW_ACCOUNT_ERROR';

export const CLEAR_ACCOUNT_SUGGESTION = 'CLEAR_ACCOUNT_SUGGESTION';

export const ACCOUNT_SUGGESTION_SELECTED = 'ACCOUNT_SUGGESTION_SELECTED';
