export const GET_ACTIVITY_DETAIL = 'GET_ACTIVITY_DETAIL';

export const GET_ACTIVITY_DETAIL_SUCCESS = 'GET_ACTIVITY_DETAIL_SUCCESS';

export const GET_ACTIVITY_DETAIL_ERROR = 'GET_ACTIVITY_DETAIL_ERROR';

export const CREATE_ACTIVITY_NOTE = 'CREATE_ACTIVITY_NOTE';

export const CREATE_ACTIVITY_NOTE_SUCCESS = 'CREATE_ACTIVITY_NOTE_SUCCESS';

export const CREATE_ACTIVITY_NOTE_ERROR = 'CREATE_ACTIVITY_NOTE_ERROR';

export const GET_ACTIVITY_DETAIL_NOTES = 'GET_ACTIVITY_DETAIL_NOTES';

export const GET_ACTIVITY_DETAIL_NOTES_SUCCESS = 'GET_ACTIVITY_DETAIL_NOTES_SUCCESS';

export const GET_ACTIVITY_DETAIL_NOTES_ERROR = 'GET_ACTIVITY_DETAIL_NOTES_ERROR';

export const UPDATE_ACTIVITY_DETAIL = 'UPDATE_ACTIVITY_DETAIL';

export const UPDATE_ACTIVITY_DETAIL_SUCCESS = 'UPDATE_ACTIVITY_DETAIL_SUCCESS';

export const UPDATE_ACTIVITY_DETAIL_ERROR = 'UPDATE_ACTIVITY_DETAIL_ERROR';
