export const RECORD_SEARCH_KEYWORD = 'RECORD_SEARCH_KEYWORD';

export const GET_ALGOLIA_LEAD = 'GET_ALGOLIA_LEAD';

export const GET_ALGOLIA_LEAD_SUCCESS = 'GET_ALGOLIA_LEAD_SUCCESS';

export const GET_ALGOLIA_LEAD_ERROR = 'GET_ALGOLIA_LEAD_ERROR';

export const CLEAR_ALGOLIA_LEAD = 'CLEAR_ALGOLIA_LEAD';

export const GET_ALGOLIA_CONTACT = 'GET_ALGOLIA_CONTACT';

export const GET_ALGOLIA_CONTACT_SUCCESS = 'GET_ALGOLIA_CONTACT_SUCCESS';

export const GET_ALGOLIA_CONTACT_ERROR = 'GET_ALGOLIA_CONTACT_ERROR';

export const CLEAR_ALGOLIA_CONTACT = 'CLEAR_ALGOLIA_CONTACT';

export const GET_ALGOLIA_ACCOUNT = 'GET_ALGOLIA_ACCOUNT';

export const GET_ALGOLIA_ACCOUNT_SUCCESS = 'GET_ALGOLIA_ACCOUNT_SUCCESS';

export const GET_ALGOLIA_ACCOUNT_ERROR = 'GET_ALGOLIA_ACCOUNT_ERROR';

export const CLEAR_ALGOLIA_ACCOUNT = 'CLEAR_ALGOLIA_ACCOUNT';

export const GET_ALGOLIA_TASK = 'GET_ALGOLIA_TASK';

export const GET_ALGOLIA_TASK_SUCCESS = 'GET_ALGOLIA_TASK_SUCCESS';

export const GET_ALGOLIA_TASK_ERROR = 'GET_ALGOLIA_TASK_ERROR';

export const CLEAR_ALGOLIA_TASK = 'CLEAR_ALGOLIA_TASK';

export const GET_ALGOLIA_EVENT = 'GET_ALGOLIA_EVENT';

export const GET_ALGOLIA_EVENT_SUCCESS = 'GET_ALGOLIA_EVENT_SUCCESS';

export const GET_ALGOLIA_EVENT_ERROR = 'GET_ALGOLIA_EVENT_ERROR';

export const CLEAR_ALGOLIA_EVENT = 'CLEAR_ALGOLIA_EVENT';

export const GET_ALGOLIA_DEAL = 'GET_ALGOLIA_DEAL';

export const GET_ALGOLIA_DEAL_SUCCESS = 'GET_ALGOLIA_DEAL_SUCCESS';

export const GET_ALGOLIA_DEAL_ERROR = 'GET_ALGOLIA_DEAL_ERROR';

export const CLEAR_ALGOLIA_DEAL = 'CLEAR_ALGOLIA_DEAL';
