// Sign in constants
export const SIGN_IN = 'SIGN_IN';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_IN_EMPTY_FIELDS_ERROR = 'SIGN_IN_EMPTY_FIELDS_ERROR';

// Sign up constants
export const SIGN_UP = 'SIGN_UP';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_UP_EMPTY_FIELDS_ERROR = 'SIGN_UP_EMPTY_FIELDS_ERROR';

export const SIGN_UP_PASSWORD_MATCHING_ERROR = 'SIGN_UP_PASSWORD_MATCHING_ERROR';

export const RESET_SIGN_UP_PASSWORD_MATCHING_ERROR = 'RESET_SIGN_UP_PASSWORD_MATCHING_ERROR';

export const SIGN_UP_THERMS_TOGGLE = 'SIGN_UP_THERMS_TOGGLE';

// Password reset constants
export const PASSWORD_RESET = 'PASSWORD_RESET';

export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';

export const PASSWORD_RESET_EMPTY_FIELDS_ERROR = 'PASSWORD_RESET_EMPTY_FIELDS_ERROR';

// Work with user data

export const SAVE_USER_DATA = 'SAVE_USER_DATA';

export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

export const SHOW_SUBSCRIPTION_NOTIFICATION = 'SHOW_SUBSCRIPTION_NOTIFICATION';

export const HIDE_SUBSCRIPTION_NOTIFICATION = 'HIDE_SUBSCRIPTION_NOTIFICATION';
