export const POST_ACCOUNT_IMAGE = 'POST_ACCOUNT_IMAGE';

export const POST_ACCOUNT_IMAGE_SUCCESS = 'POST_ACCOUNT_IMAGE_SUCCESS';

export const POST_ACCOUNT_IMAGE_ERROR = 'POST_ACCOUNT_IMAGE_ERROR';

export const ACCOUNT_IMAGE_CLEAR = 'ACCOUNT_IMAGE_CLEAR';

export const POST_LEAD_IMAGE = 'POST_LEAD_IMAGE';

export const POST_LEAD_IMAGE_SUCCESS = 'POST_LEAD_IMAGE_SUCCESS';

export const POST_LEAD_IMAGE_ERROR = 'POST_LEAD_IMAGE_ERROR';

export const LEAD_IMAGE_CLEAR = 'LEAD_IMAGE_CLEAR';

export const POST_CONTACT_IMAGE = 'POST_CONTACT_IMAGE';

export const POST_CONTACT_IMAGE_SUCCESS = 'POST_CONTACT_IMAGE_SUCCESS';

export const POST_CONTACT_IMAGE_ERROR = 'POST_CONTACT_IMAGE_ERROR';

export const CONTACT_IMAGE_CLEAR = 'CONTACT_IMAGE_CLEAR';

export const POST_USER_IMAGE = 'POST_USER_IMAGE';

export const POST_USER_IMAGE_SUCCESS = 'POST_USER_IMAGE_SUCCESS';

export const POST_USER_IMAGE_ERROR = 'POST_USER_IMAGE_ERROR';

export const USER_IMAGE_CLEAR = 'USER_IMAGE_CLEAR';

export const POST_ORG_PROFILE_IMAGE = 'POST_ORG_PROFILE_IMAGE';

export const POST_ORG_PROFILE_IMAGE_SUCCESS = 'POST_ORG_PROFILE_IMAGE_SUCCESS';

export const POST_ORG_PROFILE_IMAGE_ERROR = 'POST_ORG_PROFILE_IMAGE_ERROR';

export const ORG_PROFILE_IMAGE_CLEAR = 'ORG_PROFILE_IMAGE_CLEAR';

export const POST_EMPLOYEE_PROFILE_IMAGE = 'POST_EMPLOYEE_PROFILE_IMAGE';

export const POST_EMPLOYEE_PROFILE_IMAGE_SUCCESS = 'POST_EMPLOYEE_PROFILE_IMAGE_SUCCESS';

export const POST_EMPLOYEE_PROFILE_IMAGE_ERROR = 'POST_EMPLOYEE_PROFILE_IMAGE_ERROR';

export const EMPLOYEE_PROFILE_IMAGE_CLEAR = 'EMPLOYEE_PROFILE_IMAGE_CLEAR';

export const INIT_LEAD_CLOUDINARY_IMAGE = 'INIT_LEAD_CLOUDINARY_IMAGE';

export const INIT_ACCOUNT_CLOUDINARY_IMAGE = 'INIT_ACCOUNT_CLOUDINARY_IMAGE';

export const INIT_CONTACT_CLOUDINARY_IMAGE = 'INIT_CONTACT_CLOUDINARY_IMAGE';

