export const GET_CONTACTS_LIST = 'GET_CONTACTS_LIST';

export const SET_CURRENT_CONTACTS_LIST_TYPE = 'SET_CURRENT_CONTACTS_LIST_TYPE';

export const SET_CURRENT_CONTACTS_PAGE = 'SET_CURRENT_CONTACTS_PAGE';

export const GET_CONTACTS_LIST_SUCCESS = 'GET_CONTACTS_LIST_SUCCESS';

export const GET_CONTACTS_LIST_ERROR = 'GET_CONTACTS_LIST_ERROR';

export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';

export const CREATE_NEW_CONTACT_SUCCESS = 'CREATE_NEW_CONTACT_SUCCESS';

export const CREATE_NEW_CONTACT_ERROR = 'CREATE_NEW_CONTACT_ERROR';
