export const GET_CUSTOMER_DETAIL = 'GET_CUSTOMER_DETAIL';

export const GET_CUSTOMER_DETAIL_SUCCESS = 'GET_CUSTOMER_DETAIL_SUCCESS';

export const GET_CUSTOMER_DETAIL_ERROR = 'GET_CUSTOMER_DETAIL_ERROR';

export const UPDATE_CUSTOMER_DETAIL = 'UPDATE_CUSTOMER_DETAIL';

export const UPDATE_CUSTOMER_DETAIL_SUCCESS = 'UPDATE_CUSTOMER_DETAIL_SUCCESS';

export const UPDATE_CUSTOMER_DETAIL_ERROR = 'UPDATE_CUSTOMER_DETAIL_ERROR';

export const CONVERT_LEAD_DETAIL = 'CONVERT_LEAD_DETAIL';

export const CONVERT_LEAD_DETAIL_SUCCESS = 'CONVERT_LEAD_DETAIL_SUCCESS';

export const CONVERT_LEAD_DETAIL_ERROR = 'CONVERT_LEAD_DETAIL_ERROR';

export const GET_CUSTOMER_DETAIL_TASKS = 'GET_CUSTOMER_DETAIL_TASKS';

export const GET_CUSTOMER_DETAIL_TASKS_SUCCESS = 'GET_CUSTOMER_DETAIL_TASKS_SUCCESS';

export const GET_CUSTOMER_DETAIL_TASKS_ERROR = 'GET_CUSTOMER_DETAIL_TASKS_ERROR';

export const SET_CUSTOMER_DETAIL_TASKS_TYPE = 'SET_CUSTOMER_DETAIL_TASKS_TYPE';

export const GET_CUSTOMER_DETAIL_MEETINGS = 'GET_CUSTOMER_DETAIL_MEETINGS';

export const GET_CUSTOMER_DETAIL_MEETINGS_SUCCESS = 'GET_CUSTOMER_DETAIL_MEETINGS_SUCCESS';

export const GET_CUSTOMER_DETAIL_MEETINGS_ERROR = 'GET_CUSTOMER_DETAIL_MEETINGS_ERROR';

export const SET_CUSTOMER_DETAIL_MEETINGS_TYPE = 'SET_CUSTOMER_DETAIL_MEETINGS_TYPE';

export const GET_CUSTOMER_DETAIL_DEALS = 'GET_CUSTOMER_DETAIL_DEALS';

export const GET_CUSTOMER_DETAIL_DEALS_SUCCESS = 'GET_CUSTOMER_DETAIL_DEALS_SUCCESS';

export const GET_CUSTOMER_DETAIL_DEALS_ERROR = 'GET_CUSTOMER_DETAIL_DEALS_ERROR';

export const SET_CUSTOMER_DETAIL_DEALS_TYPE = 'SET_CUSTOMER_DETAIL_DEALS_TYPE';
