export const GET_DEALS_LIST = 'GET_DEALS_LIST';

export const SET_CURRENT_DEALS_LIST_TYPE = 'SET_CURRENT_DEALS_LIST_TYPE';

export const SET_CURRENT_DEALS_PAGE = 'SET_CURRENT_DEALS_PAGE';

export const GET_DEALS_LIST_SUCCESS = 'GET_DEALS_LIST_SUCCESS';

export const GET_DEALS_LIST_ERROR = 'GET_DEALS_LIST_ERROR';

export const CREATE_NEW_DEAL = 'CREATE_NEW_DEAL';

export const CREATE_NEW_DEAL_SUCCESS = 'CREATE_NEW_DEAL_SUCCESS';

export const CREATE_NEW_DEAL_ERROR = 'CREATE_NEW_DEAL_ERROR';

export const GET_DEALS_SUMMARY = 'GET_DEALS_SUMMARY';

export const GET_DEALS_SUMMARY_SUCCESS = 'GET_DEALS_SUMMARY_SUCCESS';

export const GET_DEALS_SUMMARY_ERROR = 'GET_DEALS_SUMMARY_ERROR';

export const UPDATE_DEAL = 'UPDATE_DEAL';

export const UPDATE_DEAL_SUCCESS = 'UPDATE_DEAL_SUCCESS';

export const UPDATE_DEAL_ERROR = 'UPDATE_DEAL_ERROR';
