export const GET_EMPLOYEES_LIST = 'GET_EMPLOYEES_LIST';

export const GET_EMPLOYEES_LIST_SUCCESS = 'GET_EMPLOYEES_LIST_SUCCESS';

export const GET_EMPLOYEES_LIST_ERROR = 'GET_EMPLOYEES_LIST_ERROR';

export const EMPLOYEES_INPUT_VALUE_CHANGED = 'EMPLOYEES_INPUT_VALUE_CHANGED';

export const EMPLOYEE_SUGGESTION_SELECTED = 'EMPLOYEE_SUGGESTION_SELECTED';

export const EMPLOYEE_FIELD_CLEAR = 'EMPLOYEE_FIELD_CLEAR';

export const EMPLOYEE_SELECTED = 'EMPLOYEE_SELECTED';

export const CLEAR_SELECTED_EMPLOYEE = 'CLEAR_SELECTED_EMPLOYEE';

export const SAVE_EMPLOYEE_CHANGES = 'SAVE_EMPLOYEE_CHANGES';

export const SAVE_EMPLOYEE_CHANGES_SUCCESS = 'SAVE_EMPLOYEE_CHANGES_SUCCESS';

export const SAVE_EMPLOYEE_CHANGES_ERROR = 'SAVE_EMPLOYEE_CHANGES_ERROR';
