export const GET_ENTITY = 'GET_ENTITY';

export const GET_ENTITY_SUCCESS = 'GET_ENTITY_SUCCESS';

export const GET_ENTITY_ERROR = 'GET_ENTITY_ERROR';

export const EDIT_ENTITY = 'EDIT_ENTITY';

export const EDIT_ENTITY_SUCCESS = 'EDIT_ENTITY_SUCCESS';

export const EDIT_ENTITY_ERROR = 'EDIT_ENTITY_ERROR';

export const GET_ENTITIES_SUMMARY = 'GET_ENTITIES_SUMMARY';

export const GET_ENTITIES_SUMMARY_SUCCESS = 'GET_ENTITIES_SUMMARY_SUCCESS';

export const GET_ENTITIES_SUMMARY_ERROR = 'GET_ENTITIES_SUMMARY_ERROR';

