export const CONTACT_CT_CHANGED = 'CONTACT_CT_CHANGED';

export const CONTACT_ID_CHANGED = 'CONTACT_ID_CHANGED';

export const CLEAR_LEAD_CONTACT_SUGGESTION = 'CLEAR_LEAD_CONTACT_SUGGESTION';

export const LEAD_CONTACT_SELECTED = 'LEAD_CONTACT_SELECTED';
