export const GET_LEADS_LIST = 'GET_LEADS_LIST';

export const GET_LEADS_LIST_SUCCESS = 'GET_LEADS_LIST_SUCCESS';

export const GET_LEADS_LIST_ERROR = 'GET_LEADS_LIST_ERROR';

export const SET_CURRENT_LEADS_LIST_TYPE = 'SET_CURRENT_LEADS_LIST_TYPE';

export const SET_CURRENT_LEADS_PAGE = 'SET_CURRENT_LEADS_PAGE';

export const CREATE_NEW_LEAD = 'CREATE_NEW_LEAD';

export const CREATE_NEW_LEAD_SUCCESS = 'CREATE_NEW_LEAD_SUCCESS';

export const CREATE_NEW_LEAD_ERROR = 'CREATE_NEW_LEAD_ERROR';

export const GET_LEADS_SUMMARY = 'GET_LEADS_SUMMARY';

export const GET_LEADS_SUMMARY_SUCCESS = 'GET_LEADS_SUMMARY_SUCCESS';

export const GET_LEADS_SUMMARY_ERROR = 'GET_LEADS_SUMMARY_ERROR';
