export const GET_MEETINGS_LIST = 'GET_MEETINGS_LIST';

export const SET_CURRENT_MEETINGS_LIST_TYPE = 'SET_CURRENT_MEETINGS_LIST_TYPE';

export const SET_CURRENT_MEETINGS_PAGE = 'SET_CURRENT_MEETINGS_PAGE';

export const GET_MEETINGS_LIST_SUCCESS = 'GET_MEETINGS_LIST_SUCCESS';

export const GET_MEETINGS_LIST_ERROR = 'GET_MEETINGS_LIST_ERROR';

export const CREATE_NEW_MEETING = 'CREATE_NEW_MEETING';

export const CREATE_NEW_MEETING_SUCCESS = 'CREATE_NEW_MEETING_SUCCESS';

export const CREATE_NEW_MEETING_ERROR = 'CREATE_NEW_MEETING_ERROR';

export const CLEAR_FORM = 'CLEAR_FORM';

export const GET_MEETING_CONTACTS = 'GET_MEETING_CONTACTS';

export const GET_MEETING_CONTACTS_SUCCESS = 'GET_MEETING_CONTACTS_SUCCESS';

export const GET_MEETING_CONTACTS_ERROR = 'GET_MEETING_CONTACTS_ERROR';

export const GET_MEETING_ACCOUNTS = 'GET_MEETING_ACCOUNTS';

export const GET_MEETING_ACCOUNTS_SUCCESS = 'GET_MEETING_ACCOUNTS_SUCCESS';

export const GET_MEETING_ACCOUNTS_ERROR = 'GET_MEETING_ACCOUNTS_ERROR';
