export const GET_MEMBERSHIPS = 'GET_MEMBERSHIPS';

export const GET_MEMBERSHIPS_SUCCESS = 'GET_MEMBERSHIPS_SUCCESS';

export const GET_MEMBERSHIPS_ERROR = 'GET_MEMBERSHIPS_ERROR';

export const EDIT_MEMBERSHIP = 'EDIT_MEMBERSHIP';

export const EDIT_MEMBERSHIP_SUCCESS = 'EDIT_MEMBERSHIP_SUCCESS';

export const EDIT_MEMBERSHIP_ERROR = 'EDIT_MEMBERSHIP_ERROR';

export const DELETE_MEMBERSHIP = 'DELETE_MEMBERSHIP';

export const DELETE_MEMBERSHIP_SUCCESS = 'DELETE_MEMBERSHIP_SUCCESS';

export const DELETE_MEMBERSHIP_ERROR = 'DELETE_MEMBERSHIP_ERROR';

export const ADD_MEMBERSHIPS = 'ADD_MEMBERSHIPS';

export const ADD_MEMBERSHIPS_SUCCESS = 'ADD_MEMBERSHIPS_SUCCESS';

export const ADD_MEMBERSHIPS_ERROR = 'ADD_MEMBERSHIPS_ERROR';
