export const SHOW_CREATE_MEETING_MODAL = 'SHOW_CREATE_MEETING_MODAL';

export const HIDE_CREATE_MEETING_MODAL = 'HIDE_CREATE_MEETING_MODAL';

export const SHOW_CREATE_TASK_MODAL = 'SHOW_CREATE_TASK_MODAL';

export const HIDE_CREATE_TASK_MODAL = 'HIDE_CREATE_TASK_MODAL';

export const SHOW_CREATE_ACCOUNT_MODAL = 'SHOW_CREATE_ACCOUNT_MODAL';

export const HIDE_CREATE_ACCOUNT_MODAL = 'HIDE_CREATE_ACCOUNT_MODAL';

export const SHOW_CREATE_CONTACT_MODAL = 'SHOW_CREATE_CONTACT_MODAL';

export const HIDE_CREATE_CONTACT_MODAL = 'HIDE_CREATE_CONTACT_MODAL';

export const SHOW_CREATE_LEAD_MODAL = 'SHOW_CREATE_LEAD_MODAL';

export const HIDE_CREATE_LEAD_MODAL = 'HIDE_CREATE_LEAD_MODAL';

export const SHOW_CREATE_USER_MODAL = 'SHOW_CREATE_USER_MODAL';

export const HIDE_CREATE_USER_MODAL = 'HIDE_CREATE_USER_MODAL';

export const SHOW_CREATE_DEAL_MODAL = 'SHOW_CREATE_DEAL_MODAL';

export const HIDE_CREATE_DEAL_MODAL = 'HIDE_CREATE_DEAL_MODAL';

export const SHOW_UPDATE_LEAD_MODAL = 'SHOW_UPDATE_LEAD_MODAL';

export const HIDE_UPDATE_LEAD_MODAL = 'HIDE_UPDATE_LEAD_MODAL';

export const SHOW_UPDATE_ACCOUNT_MODAL = 'SHOW_UPDATE_ACCOUNT_MODAL';

export const HIDE_UPDATE_ACCOUNT_MODAL = 'HIDE_UPDATE_ACCOUNT_MODAL';

export const SHOW_UPDATE_CONTACT_MODAL = 'SHOW_UPDATE_CONTACT_MODAL';

export const HIDE_UPDATE_CONTACT_MODAL = 'HIDE_UPDATE_CONTACT_MODAL';

export const SHOW_UPDATE_TASK_MODAL = 'SHOW_UPDATE_TASK_MODAL';

export const HIDE_UPDATE_TASK_MODAL = 'HIDE_UPDATE_TASK_MODAL';

export const SHOW_UPDATE_MEETING_MODAL = 'SHOW_UPDATE_MEETING_MODAL';

export const HIDE_UPDATE_MEETING_MODAL = 'HIDE_UPDATE_MEETING_MODAL';

export const SHOW_UPDATE_DEAL_MODAL = 'SHOW_UPDATE_DEAL_MODAL';

export const HIDE_UPDATE_DEAL_MODAL = 'HIDE_UPDATE_DEAL_MODAL';

export const INIT_INITIAL_MODAL_DATA = 'INIT_INITIAL_MODAL_DATA';

export const DEL_INITIAL_MODAL_DATA = 'DEL_INITIAL_MODAL_DATA';

export const SHOW_SUBSCRIPTION_CHECKOUT_MODAL = 'SHOW_SUBSCRIPTION_CHECKOUT_MODAL';

export const HIDE_SUBSCRIPTION_CHECKOUT_MODAL = 'HIDE_SUBSCRIPTION_CHECKOUT_MODAL';

export const SHOW_CLOSE_DEAL_MODAL = 'SHOW_CLOSE_DEAL_MODAL';

export const HIDE_CLOSE_DEAL_MODAL = 'HIDE_CLOSE_DEAL_MODAL';
