export const GET_TASKS_LIST = 'GET_TASKS_LIST';

export const SET_CURRENT_TASKS_LIST_TYPE = 'SET_CURRENT_TASKS_LIST_TYPE';

export const SET_CURRENT_TASKS_PAGE = 'SET_CURRENT_TASKS_PAGE';

export const GET_TASKS_LIST_SUCCESS = 'GET_TASKS_LIST_SUCCESS';

export const GET_TASKS_LIST_ERROR = 'GET_TASKS_LIST_ERROR';

export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';

export const CREATE_NEW_TASK_SUCCESS = 'CREATE_NEW_TASK_SUCCESS';

export const CREATE_NEW_TASK_ERROR = 'CREATE_NEW_TASK_ERROR';

export const GET_TASK_CONTACTS = 'GET_TASK_CONTACTS';

export const GET_TASK_CONTACTS_SUCCESS = 'GET_TASK_CONTACTS_SUCCESS';

export const GET_TASK_CONTACTS_ERROR = 'GET_TASK_CONTACTS_ERROR';

export const GET_TASK_ACCOUNTS = 'GET_TASK_ACCOUNTS';

export const GET_TASK_ACCOUNTS_SUCCESS = 'GET_TASK_ACCOUNTS_SUCCESS';

export const GET_TASK_ACCOUNTS_ERROR = 'GET_TASK_ACCOUNTS_ERROR';
