export const GET_TIME_LINE = 'GET_TIME_LINE';

export const GET_TIME_LINE_SUCCESS = 'GET_TIME_LINE_SUCCESS';

export const GET_TIME_LINE_ERROR = 'GET_TIME_LINE_ERROR';

export const CLEAR_TIME_LINE_LIST = 'CLEAR_TIME_LINE_LIST';
